config/routes.rb
Questioner::Application.routes.draw do
  put "core/choose_q1"

  put "core/choose_q2"

  put "core/choose_q3"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "show_question" => "core#show_question"

  match "show_responses" => "core#show_responses"

  root :to => 'core#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer1, :answer2, :answer3, :details, :selected,
  :score_ans1, :score_ans2, :score_ans3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/core_controller.rb
class CoreController < ApplicationController
  def index
    @title = "Home"
  end

  def show_question
    @title = "Current Question"
    @selected_question = Question.find_by_selected(true)
  end

  def show_responses
    @title = "Summary of Responses"
    @selected_question = Question.find_by_selected(true)
  end

  def choose_q1
    @selected_question = Question.find_by_selected(true)
    if @selected_question.score_ans1 == nil
      @selected_question.update_attribute(:score_ans1, 1)
    else
      new_score = @selected_question.score_ans1 + 1
      @selected_question.update_attribute(:score_ans1, new_score)
    end
    flash[:notice] = "Your Vote has been recorded!"
    redirect_to :action => "index"
  end

  def choose_q2
    @selected_question = Question.find_by_selected(true)
    if @selected_question.score_ans2 == nil
      @selected_question.update_attribute(:score_ans2, 1)
    else
      new_score = @selected_question.score_ans2 + 1
      @selected_question.update_attribute(:score_ans2, new_score)
    end
    flash[:notice] = "Your Vote has been recorded!"
    redirect_to :action => "index"
  end

  def choose_q3
    @selected_question = Question.find_by_selected(true)
    if @selected_question.score_ans3 == nil
      @selected_question.update_attribute(:score_ans3, 1)
    else
      new_score = @selected_question.score_ans3 + 1
      @selected_question.update_attribute(:score_ans3, new_score)
    end
    flash[:notice] = "Your Vote has been recorded!"
    redirect_to :action => "index"
  end

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Questioner"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/core_helper.rb
module CoreHelper
end

app/views/core/choose_q1.html.erb
<% @selected_question = Question.find_by_selected(true) %>
<h1><%= @selected_question.details %></h1>

<%= @selected_question.score_ans1 %>

app/views/core/choose_q2.html.erb
<h1>Answer#choose_q2</h1>
<p>Find me in app/views/core/choose_q2.html.erb</p>
<%= @selected_question.score_ans2 %>

app/views/core/choose_q3.html.erb
<h1>Answer#choose_q3</h1>
<p>Find me in app/views/core/choose_q3.html.erb</p>
<%= @selected_question.score_ans3 %>

app/views/core/index.html.erb
<h1>Vote To Learn</h1>
<p>
  Click the "Question" tab to view the current question.
</p>

<p>"Vote to Learn" is currently in limited Beta Test. It will be progressively
refined over the next few weeks.</p>

app/views/core/show_question.html.erb
<article>
  <% if @selected_question.nil? %>
    <h2>No question currently selected</h2>
  <% else %>
    <% question = @selected_question %>
    <h2><%= question.details %></h2>

<!-- Rails' form_tag does not seem to save much typing here, but it 
does include the Rails hack to support PUT. Don't try this in a vanilla
HTML form - it won't work just now! -->

    <%= form_tag("core/choose_q1", :method => "put") do %>
      <p class="answer">
        <%= question.answer1 %>
      </p>
      <%= submit_tag("Vote for me!") %>
    <% end %>

    <%= form_tag("core/choose_q2", :method => "put") do %>
      <p class="answer">
        <%= question.answer2 %>
      </p>
      <%= submit_tag("Vote for me!") %>
    <% end %>

    <%= form_tag("core/choose_q3", :method => "put") do %>
      <p class="answer">
        <%= question.answer3 %>
      </p>
      <%= submit_tag("Vote for me!") %>
    <% end %>
  <% end %>
</article>

app/views/core/show_responses.html.erb
<% if @selected_question.nil? %>
  <h2>No question currently selected</h2>
<% else %>
  <% question = @selected_question %>
  <h2><%= question.details %></h2>
  <p>
    <%= question.answer1 %>:
    <%= question.score_ans1 %>
  </p>

  <p>
    <%= question.answer2 %>:
    <%= question.score_ans2 %>
  </p>

  <p>
    <%= question.answer3 %>:
    <%= question.score_ans3 %>
  </p>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- _navigation.html.erb -->

<nav id="main-nav" role=navigation>
  <ul class="tabs">
    <li><h3 class="tab-label"><%= link_to "Home", root_path %></h3></li>
    <li><h3 class="tab-label"><%= link_to "Question", show_question_path %></h3></li>
    <li><h3 class="tab-label"><%= link_to "Responses", show_responses_path %></h3></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="wrapper">
    <%= render 'layouts/navigation' %>

    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <%= yield %>
  </section>
  
</body>
</html>